### ISSUE TITLE
Work on Windows 10?

### ISSUE THREAD

**Issue by manticode** [mockfs/mockfs#12]
I've followed the guidance shown at https://mockfs.github.io/ but I get FileNotFoundError always (with os.listdir('/test') ).

I am running this on Windows 10 with Python 3.11 and have attempted to mock a non-existent directory as well as an existing test directory. The results are the same.

```
import unittest
import os
import mockfs


class FSTest(unittest.TestCase):
    def setUp(self):
        self.mfs = mockfs.replace_builtins()
        self.mfs.add_entries({'/test/testfile': 'magic'})

    def tearDown(self):
        mockfs.restore_builtins()

    def test_filesystem(self):
        fh = open('/test/testfile')
        content = fh.read()
        fh.close()
        self.assertEqual(content, 'magic')


if __name__ == '__main__':
    unittest.main()
```

This returns the error:
`OSError: No such file or directory: '/test/testfile'`

**Comment by davvid** [comment]
Thanks for the heads-up. I've started looking into this a bit but I don't use Windows so my debugging reach is limited.

I can at least verify that everything's working fine on macOS and Linux with the latest versions of Python. I pushed up a few commits that modernized the test suite to help push things forward.

What you're describing pretty much sounds like the `builtins.open` function isn't getting patched, which is a little surprising. I wonder if Windows uses a slightly different symbol for the builtin open() call.

Can you try running these snippets to see in your python environment to see if it turns up any clues?

```python
import builtins
import io

print('# open')
print(open)
print(open.__module__)

print('# builtins')
print(builtins.open)

print('# io')
print(io.open)
```

We were not previously patching `io.open` directly because, on Linux at least, `io.open` is the same as `builtins.open`.

In case it helps, I pushed in a commit that also patches `io.open`. It might make a difference so please test against the main branch in case that fixed it.

**Comment by davvid** [comment]
Also, running the following from inside the test, before calling `open()`, might provide a hint:

```
print('# test open')
print(open)
print(open.__module__)
```
